# Generated by Django 5.1.4 on 2024-12-20 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpr', '0002_alter_event_img_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_contact', models.CharField(max_length=12)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('cus_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventpr.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
