# Generated by Django 5.1.4 on 2024-12-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventpr', '0003_registration_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registration_date',
        ),
    ]
