# Generated by Django 5.1.4 on 2024-12-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpr', '0004_remove_registration_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='event_img',
            field=models.ImageField(blank=True, editable=False, upload_to='pic'),
        ),
    ]
