# Generated by Django 5.1.4 on 2024-12-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventpr', '0005_registration_event_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='event_img',
        ),
    ]
