# Generated by Django 5.1.4 on 2024-12-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpr', '0007_rename_event_date_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='dateEvent',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
