# Generated by Django 5.1.4 on 2024-12-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventpr', '0012_registration_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='image',
        ),
    ]
