# Generated by Django 5.1.4 on 2024-12-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpr', '0013_remove_registration_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='cus_name',
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
