# Generated by Django 5.1.4 on 2024-12-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpr', '0014_alter_registration_cus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='event_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='pic'),
        ),
    ]
